name: openamp
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pytorch=2.5.1
  - torchaudio=2.5.1=cuda_126*
  - pandas
  - numpy
  - librosa
  - matplotlib
  - tqdm
  - pysoundfile
  - tensorboard
  - pip
  - pip:
      - auraloss
